-- =============================================================================
-- FAST TICKET · เก็บ "ส่วน" (ส่วนอำนวยการ ฯลฯ) ลงฐานข้อมูล
-- -----------------------------------------------------------------------------
-- เดิม "ส่วน" มีแค่ในตัวเลือกของฟอร์ม + ในบันทึกข้อความ PDF ไม่ได้บันทึกลง DB
-- ตาราง SECTION ใช้ชุดเดียวกันทุกสาขา (ไม่ผูกกับ DEPARTMENT)
--   TICKET.Section_ID = ส่วนตอนแจ้ง (เหมือน Dept_ID — ไม่เปลี่ยนตามผู้ใช้)
--   USER.Section_ID   = ส่วนล่าสุดของผู้ใช้ (เขียนทับทุกครั้งที่แจ้งซ่อม เหมือน USER.Dept_ID)
--
-- ⚠️ ลำดับ deploy: รันไฟล์นี้ "ก่อน" deploy AdminApi.gs เวอร์ชันที่อ้าง SECTION
-- รันซ้ำได้ ไม่เสียหาย
-- =============================================================================

BEGIN;

CREATE TABLE IF NOT EXISTS "SECTION" (
  "Section_ID"   int4 GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "Section_Name" varchar(100) NOT NULL
);
-- เหมือนตารางอื่น: เปิด RLS ไม่มี policy -> เข้าผ่าน REST API ของ Supabase ไม่ได้ ใช้ผ่าน backend เท่านั้น
ALTER TABLE "SECTION" ENABLE ROW LEVEL SECURITY;

-- id 1-5 ตรงกับ value ในตัวเลือกเดิมของฟอร์ม -> ค่าที่ผู้ใช้จำไว้ในเครื่องยังเลือกถูกตัว
INSERT INTO "SECTION" ("Section_ID", "Section_Name") VALUES
  (1, 'ส่วนอำนวยการ'),
  (2, 'ส่วนบริหารจัดเก็บภาษี'),
  (3, 'ส่วนตรวจสอบ ป้องกันและปราบปราม'),
  (4, 'ส่วนกฎหมาย'),
  (5, 'ส่วนเทคโนโลยีสารสนเทศ')
ON CONFLICT ("Section_ID") DO NOTHING;
-- ใส่ id เองแล้ว sequence ยังค้างที่ 1 (ปัญหาเดียวกับ BRANCH_pkey) -> เลื่อนให้ต่อจาก MAX
SELECT setval(pg_get_serial_sequence('"SECTION"', 'Section_ID'), (SELECT MAX("Section_ID") FROM "SECTION"));

-- ว่างได้: ตั๋ว/ผู้ใช้เดิมไม่เคยบันทึกส่วนไว้ เดาย้อนหลังไม่ได้
ALTER TABLE "TICKET" ADD COLUMN IF NOT EXISTS "Section_ID" int4
  REFERENCES "SECTION" ("Section_ID");
ALTER TABLE "USER" ADD COLUMN IF NOT EXISTS "Section_ID" int4
  REFERENCES "SECTION" ("Section_ID");
CREATE INDEX IF NOT EXISTS idx_ticket_section ON "TICKET" ("Section_ID");

COMMIT;

-- ตรวจผล: ต้องได้ 5 แถว
SELECT * FROM "SECTION" ORDER BY "Section_ID";
